language: node_js

sudo: false

branches:
  only:
    - master
    - develop

node_js:
  - '8'

install:
  - npm i npminstall && npminstall

script:
  - npm run test

after_script:
  - npm install codecov && codecov

stages:
 - name: deploy

jobs:
  include:
    - stage: deploy
      deploy:
        provider: npm
        email: "${MY_EMAIL}"
        api_key: "${NPM_TOKEN}"
        skip_cleanup: true
        on:
          branch: master