language: node_js

sudo: false,

branches:
  only:
    - master
    - develop

node_js:
  - '8'

install:
  - npm i npminstall && npminstall

stages:
 - test
 - deploy

jobs:
  include:
    - stage: test
      script:
      - npm run test

    - stage: deploy
      deploy:
        provider: npm
        email: 1095346833@qq.com
        api_key: 4acc571d-b7bb-4bc1-ba66-27c1e05e5963
        skip_cleanup: true
        on:
          branch: master

after_script:
  - npm install codecov && codecov